name: Auto Commit
on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Update File
        run: echo "$(date)" >> log.txt  # Adds the current date to log.txt

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "minaadelbis2019@gmail.com"
          git add log.txt
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"
          git push

